In [1]:
import pandas

order_reviews = pandas.read_csv("./olist_order_reviews_dataset.csv")
order_reviews.info()
order_reviews.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [2]:
review_text = order_reviews.dropna(subset=['review_comment_message']).copy()

print(f"Total de comentários reais para analisar: {len(review_text)}")
review_text['review_comment_message']

Total de comentários reais para analisar: 40977

3                    Recebi bem antes do prazo estipulado.
4        Parabéns lojas lannister adorei comprar pela I...
9        aparelho eficiente. no site a marca do aparelh...
12         Mas um pouco ,travando...pelo valor ta Boa.\r\n
15       Vendedor confiável, produto ok e entrega antes...
                               ...
99205    para este produto recebi de acordo com a compr...
99208    Entregou dentro do prazo. O produto chegou em ...
99215    O produto não foi enviado com NF, não existe v...
99221    Excelente mochila, entrega super rápida. Super...
99223    meu produto chegou e ja tenho que devolver, po...
Name: review_comment_message, Length: 40977, dtype: object

In [3]:
rates = review_text['review_score'].value_counts().sort_index()
print("Distribuição das notas nos comentários:")
print(rates)

Distribuição das notas nos comentários:
review_score
1     8745
2     2145
3     3557
4     5976
5    20554
Name: count, dtype: int64

In [4]:
orders = pandas.read_csv("./olist_orders_dataset.csv")
print(orders.info())
orders.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
order_consolided = pandas.merge(review_text,orders, on = 'order_id', how = 'left')

order_consolided['order_purchase_timestamp'] = pandas.to_datetime(order_consolided['order_purchase_timestamp'])
order_consolided['order_delivered_customer_date'] = pandas.to_datetime(order_consolided['order_delivered_customer_date'])
order_consolided['order_estimated_delivery_date'] = pandas.to_datetime(order_consolided['order_estimated_delivery_date'])

order_consolided['delivery_time'] = (order_consolided['order_delivered_customer_date'] - order_consolided['order_purchase_timestamp']).dt.days

print("Tabela unida com sucesso!")
order_consolided[['review_score', 'review_comment_message', 'delivery_time']].head()

Tabela unida com sucesso!

,review_score,review_comment_message,delivery_time
0,5,Recebi bem antes do prazo estipulado.,10.0
1,5,Parabéns lojas lannister adorei comprar pela I...,18.0
2,4,aparelho eficiente. no site a marca do aparelh...,7.0
3,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",3.0
4,5,"Vendedor confiável, produto ok e entrega antes...",3.0

In [6]:
print("Média de dias para entrega por nota:")
print(order_consolided.groupby('review_score')['delivery_time'].mean())

Média de dias para entrega por nota:
review_score
1    19.998492
2    15.632899
3    14.032464
4    12.143461
5    10.375642
Name: delivery_time, dtype: float64

In [7]:
order_consolided['delivery_delay'] = (order_consolided['order_delivered_customer_date'] - order_consolided['order_estimated_delivery_date']).dt.days
print("Média de dias de ATRASO por nota (números positivos significam atraso real):")
print(order_consolided.groupby('review_score')['delivery_delay'].mean())

Média de dias de ATRASO por nota (números positivos significam atraso real):
review_score
1    -5.056355
2    -9.216650
3   -10.725217
4   -12.581784
5   -13.643434
Name: delivery_delay, dtype: float64

In [8]:
review_1score = order_consolided[order_consolided['review_score'] == 1].copy()
review_1score_30c = review_1score[review_1score['review_comment_message'].str.len() > 30]
final_1score = review_1score_30c['review_comment_message'].dropna()

print(f"Temos {len(final_1score)} comentários detalhados de nota 1 com mais de 30 caracteres para a IA analisar.")

final_1score.to_excel('review_1score.xlsx')

Temos 7613 comentários detalhados de nota 1 com mais de 30 caracteres para a IA analisar.

In [ ]:

import seaborn as sea
import matplotlib.pyplot as plt

df_analisado = pandas.read_csv('detractor_analysis_v2.csv')

# 2. Configurar o estilo visual
sea.set_theme(style="whitegrid")
plt.figure(figsize=(12, 7))

# 3. Criar o gráfico de contagem (Countplot)
# O 'order' garante que a maior barra fique no topo (mais organizado)
grafico = sea.countplot(
    data=df_analisado, 
    y='Category', 
    order=df_analisado['Category'].value_counts().index,
    palette='viridis',
    hue='Category',
    legend=False
)

# 4. Adicionar os números (rótulos) ao final de cada barra
for i in grafico.containers:
    grafico.bar_label(i, padding=3, fontsize=12, fontweight='bold')

# 5. Personalizar títulos e eixos
plt.title('Diagnóstico de Detratores: Principais Motivos de Nota 1', fontsize=16, pad=20)
plt.xlabel('Quantidade de Ocorrências', fontsize=12)
plt.ylabel('Categoria Semântica', fontsize=12)

# Ajustar o layout para não cortar os nomes
plt.tight_layout()

# Exibir
plt.show()

ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.